[tool.poetry]
name = "notes"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.32.3"
kubernetes = "^30.1.0"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.0"
coverage = "^6.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
